#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBaiBaoKHCN
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_TCKHCN")]
	public partial class QLTapChi_KHCNDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBaiViet(BaiViet instance);
    partial void UpdateBaiViet(BaiViet instance);
    partial void DeleteBaiViet(BaiViet instance);
    partial void InsertSoTapChi(SoTapChi instance);
    partial void UpdateSoTapChi(SoTapChi instance);
    partial void DeleteSoTapChi(SoTapChi instance);
    partial void InsertChiTietBaiViet(ChiTietBaiViet instance);
    partial void UpdateChiTietBaiViet(ChiTietBaiViet instance);
    partial void DeleteChiTietBaiViet(ChiTietBaiViet instance);
    partial void InsertChiTietPhanBien(ChiTietPhanBien instance);
    partial void UpdateChiTietPhanBien(ChiTietPhanBien instance);
    partial void DeleteChiTietPhanBien(ChiTietPhanBien instance);
    partial void InsertChuyenMuc(ChuyenMuc instance);
    partial void UpdateChuyenMuc(ChuyenMuc instance);
    partial void DeleteChuyenMuc(ChuyenMuc instance);
    partial void InsertChuyenNganh(ChuyenNganh instance);
    partial void UpdateChuyenNganh(ChuyenNganh instance);
    partial void DeleteChuyenNganh(ChuyenNganh instance);
    partial void InsertDonVi(DonVi instance);
    partial void UpdateDonVi(DonVi instance);
    partial void DeleteDonVi(DonVi instance);
    partial void InsertHocHam(HocHam instance);
    partial void UpdateHocHam(HocHam instance);
    partial void DeleteHocHam(HocHam instance);
    partial void InsertHocVi(HocVi instance);
    partial void UpdateHocVi(HocVi instance);
    partial void DeleteHocVi(HocVi instance);
    partial void InsertLichSuChonNguoiPhanBien(LichSuChonNguoiPhanBien instance);
    partial void UpdateLichSuChonNguoiPhanBien(LichSuChonNguoiPhanBien instance);
    partial void DeleteLichSuChonNguoiPhanBien(LichSuChonNguoiPhanBien instance);
    partial void InsertLoaiTacGia(LoaiTacGia instance);
    partial void UpdateLoaiTacGia(LoaiTacGia instance);
    partial void DeleteLoaiTacGia(LoaiTacGia instance);
    partial void InsertNgonNgu(NgonNgu instance);
    partial void UpdateNgonNgu(NgonNgu instance);
    partial void DeleteNgonNgu(NgonNgu instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertNguoiDung_VaiTro(NguoiDung_VaiTro instance);
    partial void UpdateNguoiDung_VaiTro(NguoiDung_VaiTro instance);
    partial void DeleteNguoiDung_VaiTro(NguoiDung_VaiTro instance);
    partial void InsertQuocGia(QuocGia instance);
    partial void UpdateQuocGia(QuocGia instance);
    partial void DeleteQuocGia(QuocGia instance);
    partial void InsertVaiTro(VaiTro instance);
    partial void UpdateVaiTro(VaiTro instance);
    partial void DeleteVaiTro(VaiTro instance);
    #endregion
		
		public QLTapChi_KHCNDataContext() : 
				base(global::QuanLyBaiBaoKHCN.Properties.Settings.Default.QL_TCKHCNConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLTapChi_KHCNDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTapChi_KHCNDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTapChi_KHCNDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTapChi_KHCNDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BaiViet> BaiViets
		{
			get
			{
				return this.GetTable<BaiViet>();
			}
		}
		
		public System.Data.Linq.Table<SoTapChi> SoTapChis
		{
			get
			{
				return this.GetTable<SoTapChi>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietBaiViet> ChiTietBaiViets
		{
			get
			{
				return this.GetTable<ChiTietBaiViet>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietPhanBien> ChiTietPhanBiens
		{
			get
			{
				return this.GetTable<ChiTietPhanBien>();
			}
		}
		
		public System.Data.Linq.Table<ChuyenMuc> ChuyenMucs
		{
			get
			{
				return this.GetTable<ChuyenMuc>();
			}
		}
		
		public System.Data.Linq.Table<ChuyenNganh> ChuyenNganhs
		{
			get
			{
				return this.GetTable<ChuyenNganh>();
			}
		}
		
		public System.Data.Linq.Table<DonVi> DonVis
		{
			get
			{
				return this.GetTable<DonVi>();
			}
		}
		
		public System.Data.Linq.Table<HocHam> HocHams
		{
			get
			{
				return this.GetTable<HocHam>();
			}
		}
		
		public System.Data.Linq.Table<HocVi> HocVis
		{
			get
			{
				return this.GetTable<HocVi>();
			}
		}
		
		public System.Data.Linq.Table<LichSuChonNguoiPhanBien> LichSuChonNguoiPhanBiens
		{
			get
			{
				return this.GetTable<LichSuChonNguoiPhanBien>();
			}
		}
		
		public System.Data.Linq.Table<LoaiTacGia> LoaiTacGias
		{
			get
			{
				return this.GetTable<LoaiTacGia>();
			}
		}
		
		public System.Data.Linq.Table<NgonNgu> NgonNgus
		{
			get
			{
				return this.GetTable<NgonNgu>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung_VaiTro> NguoiDung_VaiTros
		{
			get
			{
				return this.GetTable<NguoiDung_VaiTro>();
			}
		}
		
		public System.Data.Linq.Table<QuocGia> QuocGias
		{
			get
			{
				return this.GetTable<QuocGia>();
			}
		}
		
		public System.Data.Linq.Table<VaiTro> VaiTros
		{
			get
			{
				return this.GetTable<VaiTro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BaiViet")]
	public partial class BaiViet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBaiBao;
		
		private string _MaNgonNgu;
		
		private string _MaSoTC;
		
		private string _MaChuyenMuc;
		
		private string _TieuDe;
		
		private string _TenBaiBao;
		
		private string _TenBaiBaoTiengAnh;
		
		private string _TomTat;
		
		private string _TomTatTiengAnh;
		
		private System.Nullable<System.DateTime> _NgayXetDuyet;
		
		private System.Nullable<System.DateTime> _NgayGui;
		
		private string _TuKhoa;
		
		private string _TuKhoaTiengAnh;
		
		private string _FileBaiViet;
		
		private string _TrangThai;
		
		private EntitySet<ChiTietBaiViet> _ChiTietBaiViets;
		
		private EntitySet<ChiTietPhanBien> _ChiTietPhanBiens;
		
		private EntitySet<LichSuChonNguoiPhanBien> _LichSuChonNguoiPhanBiens;
		
		private EntityRef<SoTapChi> _SoTapChi;
		
		private EntityRef<ChuyenMuc> _ChuyenMuc;
		
		private EntityRef<NgonNgu> _NgonNgu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaiBaoChanging(string value);
    partial void OnMaBaiBaoChanged();
    partial void OnMaNgonNguChanging(string value);
    partial void OnMaNgonNguChanged();
    partial void OnMaSoTCChanging(string value);
    partial void OnMaSoTCChanged();
    partial void OnMaChuyenMucChanging(string value);
    partial void OnMaChuyenMucChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnTenBaiBaoChanging(string value);
    partial void OnTenBaiBaoChanged();
    partial void OnTenBaiBaoTiengAnhChanging(string value);
    partial void OnTenBaiBaoTiengAnhChanged();
    partial void OnTomTatChanging(string value);
    partial void OnTomTatChanged();
    partial void OnTomTatTiengAnhChanging(string value);
    partial void OnTomTatTiengAnhChanged();
    partial void OnNgayXetDuyetChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXetDuyetChanged();
    partial void OnNgayGuiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGuiChanged();
    partial void OnTuKhoaChanging(string value);
    partial void OnTuKhoaChanged();
    partial void OnTuKhoaTiengAnhChanging(string value);
    partial void OnTuKhoaTiengAnhChanged();
    partial void OnFileBaiVietChanging(string value);
    partial void OnFileBaiVietChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public BaiViet()
		{
			this._ChiTietBaiViets = new EntitySet<ChiTietBaiViet>(new Action<ChiTietBaiViet>(this.attach_ChiTietBaiViets), new Action<ChiTietBaiViet>(this.detach_ChiTietBaiViets));
			this._ChiTietPhanBiens = new EntitySet<ChiTietPhanBien>(new Action<ChiTietPhanBien>(this.attach_ChiTietPhanBiens), new Action<ChiTietPhanBien>(this.detach_ChiTietPhanBiens));
			this._LichSuChonNguoiPhanBiens = new EntitySet<LichSuChonNguoiPhanBien>(new Action<LichSuChonNguoiPhanBien>(this.attach_LichSuChonNguoiPhanBiens), new Action<LichSuChonNguoiPhanBien>(this.detach_LichSuChonNguoiPhanBiens));
			this._SoTapChi = default(EntityRef<SoTapChi>);
			this._ChuyenMuc = default(EntityRef<ChuyenMuc>);
			this._NgonNgu = default(EntityRef<NgonNgu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaiBao", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaiBao
		{
			get
			{
				return this._MaBaiBao;
			}
			set
			{
				if ((this._MaBaiBao != value))
				{
					this.OnMaBaiBaoChanging(value);
					this.SendPropertyChanging();
					this._MaBaiBao = value;
					this.SendPropertyChanged("MaBaiBao");
					this.OnMaBaiBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNgonNgu", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNgonNgu
		{
			get
			{
				return this._MaNgonNgu;
			}
			set
			{
				if ((this._MaNgonNgu != value))
				{
					if (this._NgonNgu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNgonNguChanging(value);
					this.SendPropertyChanging();
					this._MaNgonNgu = value;
					this.SendPropertyChanged("MaNgonNgu");
					this.OnMaNgonNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoTC", DbType="VarChar(10)")]
		public string MaSoTC
		{
			get
			{
				return this._MaSoTC;
			}
			set
			{
				if ((this._MaSoTC != value))
				{
					if (this._SoTapChi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSoTCChanging(value);
					this.SendPropertyChanging();
					this._MaSoTC = value;
					this.SendPropertyChanged("MaSoTC");
					this.OnMaSoTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenMuc", DbType="VarChar(10)")]
		public string MaChuyenMuc
		{
			get
			{
				return this._MaChuyenMuc;
			}
			set
			{
				if ((this._MaChuyenMuc != value))
				{
					if (this._ChuyenMuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChuyenMucChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenMuc = value;
					this.SendPropertyChanged("MaChuyenMuc");
					this.OnMaChuyenMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(200)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBaiBao", DbType="NVarChar(100)")]
		public string TenBaiBao
		{
			get
			{
				return this._TenBaiBao;
			}
			set
			{
				if ((this._TenBaiBao != value))
				{
					this.OnTenBaiBaoChanging(value);
					this.SendPropertyChanging();
					this._TenBaiBao = value;
					this.SendPropertyChanged("TenBaiBao");
					this.OnTenBaiBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBaiBaoTiengAnh", DbType="VarChar(100)")]
		public string TenBaiBaoTiengAnh
		{
			get
			{
				return this._TenBaiBaoTiengAnh;
			}
			set
			{
				if ((this._TenBaiBaoTiengAnh != value))
				{
					this.OnTenBaiBaoTiengAnhChanging(value);
					this.SendPropertyChanging();
					this._TenBaiBaoTiengAnh = value;
					this.SendPropertyChanged("TenBaiBaoTiengAnh");
					this.OnTenBaiBaoTiengAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TomTat", DbType="NVarChar(MAX)")]
		public string TomTat
		{
			get
			{
				return this._TomTat;
			}
			set
			{
				if ((this._TomTat != value))
				{
					this.OnTomTatChanging(value);
					this.SendPropertyChanging();
					this._TomTat = value;
					this.SendPropertyChanged("TomTat");
					this.OnTomTatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TomTatTiengAnh", DbType="VarChar(MAX)")]
		public string TomTatTiengAnh
		{
			get
			{
				return this._TomTatTiengAnh;
			}
			set
			{
				if ((this._TomTatTiengAnh != value))
				{
					this.OnTomTatTiengAnhChanging(value);
					this.SendPropertyChanging();
					this._TomTatTiengAnh = value;
					this.SendPropertyChanged("TomTatTiengAnh");
					this.OnTomTatTiengAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXetDuyet", DbType="Date")]
		public System.Nullable<System.DateTime> NgayXetDuyet
		{
			get
			{
				return this._NgayXetDuyet;
			}
			set
			{
				if ((this._NgayXetDuyet != value))
				{
					this.OnNgayXetDuyetChanging(value);
					this.SendPropertyChanging();
					this._NgayXetDuyet = value;
					this.SendPropertyChanged("NgayXetDuyet");
					this.OnNgayXetDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGui", DbType="Date")]
		public System.Nullable<System.DateTime> NgayGui
		{
			get
			{
				return this._NgayGui;
			}
			set
			{
				if ((this._NgayGui != value))
				{
					this.OnNgayGuiChanging(value);
					this.SendPropertyChanging();
					this._NgayGui = value;
					this.SendPropertyChanged("NgayGui");
					this.OnNgayGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuKhoa", DbType="NVarChar(200)")]
		public string TuKhoa
		{
			get
			{
				return this._TuKhoa;
			}
			set
			{
				if ((this._TuKhoa != value))
				{
					this.OnTuKhoaChanging(value);
					this.SendPropertyChanging();
					this._TuKhoa = value;
					this.SendPropertyChanged("TuKhoa");
					this.OnTuKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuKhoaTiengAnh", DbType="NVarChar(200)")]
		public string TuKhoaTiengAnh
		{
			get
			{
				return this._TuKhoaTiengAnh;
			}
			set
			{
				if ((this._TuKhoaTiengAnh != value))
				{
					this.OnTuKhoaTiengAnhChanging(value);
					this.SendPropertyChanging();
					this._TuKhoaTiengAnh = value;
					this.SendPropertyChanged("TuKhoaTiengAnh");
					this.OnTuKhoaTiengAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileBaiViet", DbType="VarChar(255)")]
		public string FileBaiViet
		{
			get
			{
				return this._FileBaiViet;
			}
			set
			{
				if ((this._FileBaiViet != value))
				{
					this.OnFileBaiVietChanging(value);
					this.SendPropertyChanging();
					this._FileBaiViet = value;
					this.SendPropertyChanged("FileBaiViet");
					this.OnFileBaiVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BaiViet_ChiTietBaiViet", Storage="_ChiTietBaiViets", ThisKey="MaBaiBao", OtherKey="MaBaiBao")]
		public EntitySet<ChiTietBaiViet> ChiTietBaiViets
		{
			get
			{
				return this._ChiTietBaiViets;
			}
			set
			{
				this._ChiTietBaiViets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BaiViet_ChiTietPhanBien", Storage="_ChiTietPhanBiens", ThisKey="MaBaiBao", OtherKey="MaBaiBao")]
		public EntitySet<ChiTietPhanBien> ChiTietPhanBiens
		{
			get
			{
				return this._ChiTietPhanBiens;
			}
			set
			{
				this._ChiTietPhanBiens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BaiViet_LichSuChonNguoiPhanBien", Storage="_LichSuChonNguoiPhanBiens", ThisKey="MaBaiBao", OtherKey="MaBaiBao")]
		public EntitySet<LichSuChonNguoiPhanBien> LichSuChonNguoiPhanBiens
		{
			get
			{
				return this._LichSuChonNguoiPhanBiens;
			}
			set
			{
				this._LichSuChonNguoiPhanBiens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SoTapChi_BaiViet", Storage="_SoTapChi", ThisKey="MaSoTC", OtherKey="MaSoTC", IsForeignKey=true)]
		public SoTapChi SoTapChi
		{
			get
			{
				return this._SoTapChi.Entity;
			}
			set
			{
				SoTapChi previousValue = this._SoTapChi.Entity;
				if (((previousValue != value) 
							|| (this._SoTapChi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SoTapChi.Entity = null;
						previousValue.BaiViets.Remove(this);
					}
					this._SoTapChi.Entity = value;
					if ((value != null))
					{
						value.BaiViets.Add(this);
						this._MaSoTC = value.MaSoTC;
					}
					else
					{
						this._MaSoTC = default(string);
					}
					this.SendPropertyChanged("SoTapChi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenMuc_BaiViet", Storage="_ChuyenMuc", ThisKey="MaChuyenMuc", OtherKey="MaChuyenMuc", IsForeignKey=true)]
		public ChuyenMuc ChuyenMuc
		{
			get
			{
				return this._ChuyenMuc.Entity;
			}
			set
			{
				ChuyenMuc previousValue = this._ChuyenMuc.Entity;
				if (((previousValue != value) 
							|| (this._ChuyenMuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuyenMuc.Entity = null;
						previousValue.BaiViets.Remove(this);
					}
					this._ChuyenMuc.Entity = value;
					if ((value != null))
					{
						value.BaiViets.Add(this);
						this._MaChuyenMuc = value.MaChuyenMuc;
					}
					else
					{
						this._MaChuyenMuc = default(string);
					}
					this.SendPropertyChanged("ChuyenMuc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NgonNgu_BaiViet", Storage="_NgonNgu", ThisKey="MaNgonNgu", OtherKey="MaNgonNgu", IsForeignKey=true)]
		public NgonNgu NgonNgu
		{
			get
			{
				return this._NgonNgu.Entity;
			}
			set
			{
				NgonNgu previousValue = this._NgonNgu.Entity;
				if (((previousValue != value) 
							|| (this._NgonNgu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NgonNgu.Entity = null;
						previousValue.BaiViets.Remove(this);
					}
					this._NgonNgu.Entity = value;
					if ((value != null))
					{
						value.BaiViets.Add(this);
						this._MaNgonNgu = value.MaNgonNgu;
					}
					else
					{
						this._MaNgonNgu = default(string);
					}
					this.SendPropertyChanged("NgonNgu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietBaiViets(ChiTietBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.BaiViet = this;
		}
		
		private void detach_ChiTietBaiViets(ChiTietBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.BaiViet = null;
		}
		
		private void attach_ChiTietPhanBiens(ChiTietPhanBien entity)
		{
			this.SendPropertyChanging();
			entity.BaiViet = this;
		}
		
		private void detach_ChiTietPhanBiens(ChiTietPhanBien entity)
		{
			this.SendPropertyChanging();
			entity.BaiViet = null;
		}
		
		private void attach_LichSuChonNguoiPhanBiens(LichSuChonNguoiPhanBien entity)
		{
			this.SendPropertyChanging();
			entity.BaiViet = this;
		}
		
		private void detach_LichSuChonNguoiPhanBiens(LichSuChonNguoiPhanBien entity)
		{
			this.SendPropertyChanging();
			entity.BaiViet = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoTapChi")]
	public partial class SoTapChi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSoTC;
		
		private string _TenSo;
		
		private string _AnhBia;
		
		private System.Nullable<System.DateTime> _NgayXuatBan;
		
		private EntitySet<BaiViet> _BaiViets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSoTCChanging(string value);
    partial void OnMaSoTCChanged();
    partial void OnTenSoChanging(string value);
    partial void OnTenSoChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    partial void OnNgayXuatBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuatBanChanged();
    #endregion
		
		public SoTapChi()
		{
			this._BaiViets = new EntitySet<BaiViet>(new Action<BaiViet>(this.attach_BaiViets), new Action<BaiViet>(this.detach_BaiViets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoTC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSoTC
		{
			get
			{
				return this._MaSoTC;
			}
			set
			{
				if ((this._MaSoTC != value))
				{
					this.OnMaSoTCChanging(value);
					this.SendPropertyChanging();
					this._MaSoTC = value;
					this.SendPropertyChanged("MaSoTC");
					this.OnMaSoTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSo", DbType="NVarChar(100)")]
		public string TenSo
		{
			get
			{
				return this._TenSo;
			}
			set
			{
				if ((this._TenSo != value))
				{
					this.OnTenSoChanging(value);
					this.SendPropertyChanging();
					this._TenSo = value;
					this.SendPropertyChanged("TenSo");
					this.OnTenSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="VarChar(200)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuatBan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayXuatBan
		{
			get
			{
				return this._NgayXuatBan;
			}
			set
			{
				if ((this._NgayXuatBan != value))
				{
					this.OnNgayXuatBanChanging(value);
					this.SendPropertyChanging();
					this._NgayXuatBan = value;
					this.SendPropertyChanged("NgayXuatBan");
					this.OnNgayXuatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SoTapChi_BaiViet", Storage="_BaiViets", ThisKey="MaSoTC", OtherKey="MaSoTC")]
		public EntitySet<BaiViet> BaiViets
		{
			get
			{
				return this._BaiViets;
			}
			set
			{
				this._BaiViets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BaiViets(BaiViet entity)
		{
			this.SendPropertyChanging();
			entity.SoTapChi = this;
		}
		
		private void detach_BaiViets(BaiViet entity)
		{
			this.SendPropertyChanging();
			entity.SoTapChi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietBaiViet")]
	public partial class ChiTietBaiViet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBaiBao;
		
		private string _MaNguoiDung;
		
		private string _MaLTacGia;
		
		private EntityRef<BaiViet> _BaiViet;
		
		private EntityRef<LoaiTacGia> _LoaiTacGia;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaiBaoChanging(string value);
    partial void OnMaBaiBaoChanged();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnMaLTacGiaChanging(string value);
    partial void OnMaLTacGiaChanged();
    #endregion
		
		public ChiTietBaiViet()
		{
			this._BaiViet = default(EntityRef<BaiViet>);
			this._LoaiTacGia = default(EntityRef<LoaiTacGia>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaiBao", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaiBao
		{
			get
			{
				return this._MaBaiBao;
			}
			set
			{
				if ((this._MaBaiBao != value))
				{
					if (this._BaiViet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBaiBaoChanging(value);
					this.SendPropertyChanging();
					this._MaBaiBao = value;
					this.SendPropertyChanged("MaBaiBao");
					this.OnMaBaiBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLTacGia", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLTacGia
		{
			get
			{
				return this._MaLTacGia;
			}
			set
			{
				if ((this._MaLTacGia != value))
				{
					if (this._LoaiTacGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLTacGiaChanging(value);
					this.SendPropertyChanging();
					this._MaLTacGia = value;
					this.SendPropertyChanged("MaLTacGia");
					this.OnMaLTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BaiViet_ChiTietBaiViet", Storage="_BaiViet", ThisKey="MaBaiBao", OtherKey="MaBaiBao", IsForeignKey=true)]
		public BaiViet BaiViet
		{
			get
			{
				return this._BaiViet.Entity;
			}
			set
			{
				BaiViet previousValue = this._BaiViet.Entity;
				if (((previousValue != value) 
							|| (this._BaiViet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BaiViet.Entity = null;
						previousValue.ChiTietBaiViets.Remove(this);
					}
					this._BaiViet.Entity = value;
					if ((value != null))
					{
						value.ChiTietBaiViets.Add(this);
						this._MaBaiBao = value.MaBaiBao;
					}
					else
					{
						this._MaBaiBao = default(string);
					}
					this.SendPropertyChanged("BaiViet");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTacGia_ChiTietBaiViet", Storage="_LoaiTacGia", ThisKey="MaLTacGia", OtherKey="MaLTacGia", IsForeignKey=true)]
		public LoaiTacGia LoaiTacGia
		{
			get
			{
				return this._LoaiTacGia.Entity;
			}
			set
			{
				LoaiTacGia previousValue = this._LoaiTacGia.Entity;
				if (((previousValue != value) 
							|| (this._LoaiTacGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiTacGia.Entity = null;
						previousValue.ChiTietBaiViets.Remove(this);
					}
					this._LoaiTacGia.Entity = value;
					if ((value != null))
					{
						value.ChiTietBaiViets.Add(this);
						this._MaLTacGia = value.MaLTacGia;
					}
					else
					{
						this._MaLTacGia = default(string);
					}
					this.SendPropertyChanged("LoaiTacGia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_ChiTietBaiViet", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.ChiTietBaiViets.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.ChiTietBaiViets.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhanBien")]
	public partial class ChiTietPhanBien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBaiBao;
		
		private string _MaNguoiDung;
		
		private string _KetQuaPhanBien;
		
		private string _YKienPhanBien;
		
		private System.Nullable<System.DateTime> _NgayPhanBien;
		
		private string _FilePhanBien;
		
		private EntityRef<BaiViet> _BaiViet;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaiBaoChanging(string value);
    partial void OnMaBaiBaoChanged();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnKetQuaPhanBienChanging(string value);
    partial void OnKetQuaPhanBienChanged();
    partial void OnYKienPhanBienChanging(string value);
    partial void OnYKienPhanBienChanged();
    partial void OnNgayPhanBienChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayPhanBienChanged();
    partial void OnFilePhanBienChanging(string value);
    partial void OnFilePhanBienChanged();
    #endregion
		
		public ChiTietPhanBien()
		{
			this._BaiViet = default(EntityRef<BaiViet>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaiBao", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaiBao
		{
			get
			{
				return this._MaBaiBao;
			}
			set
			{
				if ((this._MaBaiBao != value))
				{
					if (this._BaiViet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBaiBaoChanging(value);
					this.SendPropertyChanging();
					this._MaBaiBao = value;
					this.SendPropertyChanged("MaBaiBao");
					this.OnMaBaiBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetQuaPhanBien", DbType="NVarChar(50)")]
		public string KetQuaPhanBien
		{
			get
			{
				return this._KetQuaPhanBien;
			}
			set
			{
				if ((this._KetQuaPhanBien != value))
				{
					this.OnKetQuaPhanBienChanging(value);
					this.SendPropertyChanging();
					this._KetQuaPhanBien = value;
					this.SendPropertyChanged("KetQuaPhanBien");
					this.OnKetQuaPhanBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YKienPhanBien", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string YKienPhanBien
		{
			get
			{
				return this._YKienPhanBien;
			}
			set
			{
				if ((this._YKienPhanBien != value))
				{
					this.OnYKienPhanBienChanging(value);
					this.SendPropertyChanging();
					this._YKienPhanBien = value;
					this.SendPropertyChanged("YKienPhanBien");
					this.OnYKienPhanBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayPhanBien", DbType="Date")]
		public System.Nullable<System.DateTime> NgayPhanBien
		{
			get
			{
				return this._NgayPhanBien;
			}
			set
			{
				if ((this._NgayPhanBien != value))
				{
					this.OnNgayPhanBienChanging(value);
					this.SendPropertyChanging();
					this._NgayPhanBien = value;
					this.SendPropertyChanged("NgayPhanBien");
					this.OnNgayPhanBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilePhanBien", DbType="VarChar(255)")]
		public string FilePhanBien
		{
			get
			{
				return this._FilePhanBien;
			}
			set
			{
				if ((this._FilePhanBien != value))
				{
					this.OnFilePhanBienChanging(value);
					this.SendPropertyChanging();
					this._FilePhanBien = value;
					this.SendPropertyChanged("FilePhanBien");
					this.OnFilePhanBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BaiViet_ChiTietPhanBien", Storage="_BaiViet", ThisKey="MaBaiBao", OtherKey="MaBaiBao", IsForeignKey=true)]
		public BaiViet BaiViet
		{
			get
			{
				return this._BaiViet.Entity;
			}
			set
			{
				BaiViet previousValue = this._BaiViet.Entity;
				if (((previousValue != value) 
							|| (this._BaiViet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BaiViet.Entity = null;
						previousValue.ChiTietPhanBiens.Remove(this);
					}
					this._BaiViet.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhanBiens.Add(this);
						this._MaBaiBao = value.MaBaiBao;
					}
					else
					{
						this._MaBaiBao = default(string);
					}
					this.SendPropertyChanged("BaiViet");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_ChiTietPhanBien", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.ChiTietPhanBiens.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhanBiens.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuyenMuc")]
	public partial class ChuyenMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaChuyenMuc;
		
		private string _TenChuyenMuc;
		
		private EntitySet<BaiViet> _BaiViets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChuyenMucChanging(string value);
    partial void OnMaChuyenMucChanged();
    partial void OnTenChuyenMucChanging(string value);
    partial void OnTenChuyenMucChanged();
    #endregion
		
		public ChuyenMuc()
		{
			this._BaiViets = new EntitySet<BaiViet>(new Action<BaiViet>(this.attach_BaiViets), new Action<BaiViet>(this.detach_BaiViets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenMuc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaChuyenMuc
		{
			get
			{
				return this._MaChuyenMuc;
			}
			set
			{
				if ((this._MaChuyenMuc != value))
				{
					this.OnMaChuyenMucChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenMuc = value;
					this.SendPropertyChanged("MaChuyenMuc");
					this.OnMaChuyenMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuyenMuc", DbType="NVarChar(100)")]
		public string TenChuyenMuc
		{
			get
			{
				return this._TenChuyenMuc;
			}
			set
			{
				if ((this._TenChuyenMuc != value))
				{
					this.OnTenChuyenMucChanging(value);
					this.SendPropertyChanging();
					this._TenChuyenMuc = value;
					this.SendPropertyChanged("TenChuyenMuc");
					this.OnTenChuyenMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenMuc_BaiViet", Storage="_BaiViets", ThisKey="MaChuyenMuc", OtherKey="MaChuyenMuc")]
		public EntitySet<BaiViet> BaiViets
		{
			get
			{
				return this._BaiViets;
			}
			set
			{
				this._BaiViets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BaiViets(BaiViet entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenMuc = this;
		}
		
		private void detach_BaiViets(BaiViet entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenMuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuyenNganh")]
	public partial class ChuyenNganh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaChuyenNganh;
		
		private string _TenChuyenNganh;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChuyenNganhChanging(string value);
    partial void OnMaChuyenNganhChanged();
    partial void OnTenChuyenNganhChanging(string value);
    partial void OnTenChuyenNganhChanged();
    #endregion
		
		public ChuyenNganh()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenNganh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaChuyenNganh
		{
			get
			{
				return this._MaChuyenNganh;
			}
			set
			{
				if ((this._MaChuyenNganh != value))
				{
					this.OnMaChuyenNganhChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenNganh = value;
					this.SendPropertyChanged("MaChuyenNganh");
					this.OnMaChuyenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuyenNganh", DbType="VarChar(50)")]
		public string TenChuyenNganh
		{
			get
			{
				return this._TenChuyenNganh;
			}
			set
			{
				if ((this._TenChuyenNganh != value))
				{
					this.OnTenChuyenNganhChanging(value);
					this.SendPropertyChanging();
					this._TenChuyenNganh = value;
					this.SendPropertyChanged("TenChuyenNganh");
					this.OnTenChuyenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenNganh_NguoiDung", Storage="_NguoiDungs", ThisKey="MaChuyenNganh", OtherKey="MaChuyenNganh")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenNganh1 = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.ChuyenNganh1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonVi")]
	public partial class DonVi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDonVi;
		
		private string _TenDonVi;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonViChanging(string value);
    partial void OnMaDonViChanged();
    partial void OnTenDonViChanging(string value);
    partial void OnTenDonViChanged();
    #endregion
		
		public DonVi()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					this.OnMaDonViChanging(value);
					this.SendPropertyChanging();
					this._MaDonVi = value;
					this.SendPropertyChanged("MaDonVi");
					this.OnMaDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonVi", DbType="VarChar(50)")]
		public string TenDonVi
		{
			get
			{
				return this._TenDonVi;
			}
			set
			{
				if ((this._TenDonVi != value))
				{
					this.OnTenDonViChanging(value);
					this.SendPropertyChanging();
					this._TenDonVi = value;
					this.SendPropertyChanged("TenDonVi");
					this.OnTenDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonVi_NguoiDung", Storage="_NguoiDungs", ThisKey="MaDonVi", OtherKey="MaDonVi")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.DonVi1 = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.DonVi1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocHam")]
	public partial class HocHam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHocHam;
		
		private string _TenHocHam;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHocHamChanging(string value);
    partial void OnMaHocHamChanged();
    partial void OnTenHocHamChanging(string value);
    partial void OnTenHocHamChanged();
    #endregion
		
		public HocHam()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocHam", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHocHam
		{
			get
			{
				return this._MaHocHam;
			}
			set
			{
				if ((this._MaHocHam != value))
				{
					this.OnMaHocHamChanging(value);
					this.SendPropertyChanging();
					this._MaHocHam = value;
					this.SendPropertyChanged("MaHocHam");
					this.OnMaHocHamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHocHam", DbType="NVarChar(50)")]
		public string TenHocHam
		{
			get
			{
				return this._TenHocHam;
			}
			set
			{
				if ((this._TenHocHam != value))
				{
					this.OnTenHocHamChanging(value);
					this.SendPropertyChanging();
					this._TenHocHam = value;
					this.SendPropertyChanged("TenHocHam");
					this.OnTenHocHamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocHam_NguoiDung", Storage="_NguoiDungs", ThisKey="MaHocHam", OtherKey="MaHocHam")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.HocHam = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.HocHam = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocVi")]
	public partial class HocVi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHocVi;
		
		private string _TenHocVi;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHocViChanging(string value);
    partial void OnMaHocViChanged();
    partial void OnTenHocViChanging(string value);
    partial void OnTenHocViChanged();
    #endregion
		
		public HocVi()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocVi", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHocVi
		{
			get
			{
				return this._MaHocVi;
			}
			set
			{
				if ((this._MaHocVi != value))
				{
					this.OnMaHocViChanging(value);
					this.SendPropertyChanging();
					this._MaHocVi = value;
					this.SendPropertyChanged("MaHocVi");
					this.OnMaHocViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHocVi", DbType="NVarChar(50)")]
		public string TenHocVi
		{
			get
			{
				return this._TenHocVi;
			}
			set
			{
				if ((this._TenHocVi != value))
				{
					this.OnTenHocViChanging(value);
					this.SendPropertyChanging();
					this._TenHocVi = value;
					this.SendPropertyChanged("TenHocVi");
					this.OnTenHocViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVi_NguoiDung", Storage="_NguoiDungs", ThisKey="MaHocVi", OtherKey="MaHocVi")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.HocVi = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.HocVi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichSuChonNguoiPhanBien")]
	public partial class LichSuChonNguoiPhanBien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDung;
		
		private string _MaBaiBao;
		
		private string _TrangThai;
		
		private EntityRef<BaiViet> _BaiViet;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnMaBaiBaoChanging(string value);
    partial void OnMaBaiBaoChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public LichSuChonNguoiPhanBien()
		{
			this._BaiViet = default(EntityRef<BaiViet>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaiBao", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaiBao
		{
			get
			{
				return this._MaBaiBao;
			}
			set
			{
				if ((this._MaBaiBao != value))
				{
					if (this._BaiViet.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBaiBaoChanging(value);
					this.SendPropertyChanging();
					this._MaBaiBao = value;
					this.SendPropertyChanged("MaBaiBao");
					this.OnMaBaiBaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BaiViet_LichSuChonNguoiPhanBien", Storage="_BaiViet", ThisKey="MaBaiBao", OtherKey="MaBaiBao", IsForeignKey=true)]
		public BaiViet BaiViet
		{
			get
			{
				return this._BaiViet.Entity;
			}
			set
			{
				BaiViet previousValue = this._BaiViet.Entity;
				if (((previousValue != value) 
							|| (this._BaiViet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BaiViet.Entity = null;
						previousValue.LichSuChonNguoiPhanBiens.Remove(this);
					}
					this._BaiViet.Entity = value;
					if ((value != null))
					{
						value.LichSuChonNguoiPhanBiens.Add(this);
						this._MaBaiBao = value.MaBaiBao;
					}
					else
					{
						this._MaBaiBao = default(string);
					}
					this.SendPropertyChanged("BaiViet");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_LichSuChonNguoiPhanBien", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.LichSuChonNguoiPhanBiens.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.LichSuChonNguoiPhanBiens.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiTacGia")]
	public partial class LoaiTacGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLTacGia;
		
		private string _TenLoai;
		
		private EntitySet<ChiTietBaiViet> _ChiTietBaiViets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLTacGiaChanging(string value);
    partial void OnMaLTacGiaChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public LoaiTacGia()
		{
			this._ChiTietBaiViets = new EntitySet<ChiTietBaiViet>(new Action<ChiTietBaiViet>(this.attach_ChiTietBaiViets), new Action<ChiTietBaiViet>(this.detach_ChiTietBaiViets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLTacGia", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLTacGia
		{
			get
			{
				return this._MaLTacGia;
			}
			set
			{
				if ((this._MaLTacGia != value))
				{
					this.OnMaLTacGiaChanging(value);
					this.SendPropertyChanging();
					this._MaLTacGia = value;
					this.SendPropertyChanged("MaLTacGia");
					this.OnMaLTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiTacGia_ChiTietBaiViet", Storage="_ChiTietBaiViets", ThisKey="MaLTacGia", OtherKey="MaLTacGia")]
		public EntitySet<ChiTietBaiViet> ChiTietBaiViets
		{
			get
			{
				return this._ChiTietBaiViets;
			}
			set
			{
				this._ChiTietBaiViets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietBaiViets(ChiTietBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTacGia = this;
		}
		
		private void detach_ChiTietBaiViets(ChiTietBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.LoaiTacGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NgonNgu")]
	public partial class NgonNgu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNgonNgu;
		
		private string _TenNgonNgu;
		
		private EntitySet<BaiViet> _BaiViets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNgonNguChanging(string value);
    partial void OnMaNgonNguChanged();
    partial void OnTenNgonNguChanging(string value);
    partial void OnTenNgonNguChanged();
    #endregion
		
		public NgonNgu()
		{
			this._BaiViets = new EntitySet<BaiViet>(new Action<BaiViet>(this.attach_BaiViets), new Action<BaiViet>(this.detach_BaiViets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNgonNgu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNgonNgu
		{
			get
			{
				return this._MaNgonNgu;
			}
			set
			{
				if ((this._MaNgonNgu != value))
				{
					this.OnMaNgonNguChanging(value);
					this.SendPropertyChanging();
					this._MaNgonNgu = value;
					this.SendPropertyChanged("MaNgonNgu");
					this.OnMaNgonNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNgonNgu", DbType="NVarChar(50)")]
		public string TenNgonNgu
		{
			get
			{
				return this._TenNgonNgu;
			}
			set
			{
				if ((this._TenNgonNgu != value))
				{
					this.OnTenNgonNguChanging(value);
					this.SendPropertyChanging();
					this._TenNgonNgu = value;
					this.SendPropertyChanged("TenNgonNgu");
					this.OnTenNgonNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NgonNgu_BaiViet", Storage="_BaiViets", ThisKey="MaNgonNgu", OtherKey="MaNgonNgu")]
		public EntitySet<BaiViet> BaiViets
		{
			get
			{
				return this._BaiViets;
			}
			set
			{
				this._BaiViets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BaiViets(BaiViet entity)
		{
			this.SendPropertyChanging();
			entity.NgonNgu = this;
		}
		
		private void detach_BaiViets(BaiViet entity)
		{
			this.SendPropertyChanging();
			entity.NgonNgu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDung;
		
		private string _MaHocVi;
		
		private string _MaHocHam;
		
		private string _MaDonVi;
		
		private string _MaChuyenNganh;
		
		private string _MaQG;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private string _Email;
		
		private string _CCCD;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private string _ChuyenNganh;
		
		private string _DonVi;
		
		private string _QuocGia;
		
		private string _GioiTinh;
		
		private EntitySet<ChiTietBaiViet> _ChiTietBaiViets;
		
		private EntitySet<ChiTietPhanBien> _ChiTietPhanBiens;
		
		private EntitySet<LichSuChonNguoiPhanBien> _LichSuChonNguoiPhanBiens;
		
		private EntitySet<NguoiDung_VaiTro> _NguoiDung_VaiTros;
		
		private EntityRef<ChuyenNganh> _ChuyenNganh1;
		
		private EntityRef<DonVi> _DonVi1;
		
		private EntityRef<HocVi> _HocVi;
		
		private EntityRef<HocHam> _HocHam;
		
		private EntityRef<QuocGia> _QuocGia1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnMaHocViChanging(string value);
    partial void OnMaHocViChanged();
    partial void OnMaHocHamChanging(string value);
    partial void OnMaHocHamChanged();
    partial void OnMaDonViChanging(string value);
    partial void OnMaDonViChanged();
    partial void OnMaChuyenNganhChanging(string value);
    partial void OnMaChuyenNganhChanged();
    partial void OnMaQGChanging(string value);
    partial void OnMaQGChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnChuyenNganhChanging(string value);
    partial void OnChuyenNganhChanged();
    partial void OnDonViChanging(string value);
    partial void OnDonViChanged();
    partial void OnQuocGiaChanging(string value);
    partial void OnQuocGiaChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    #endregion
		
		public NguoiDung()
		{
			this._ChiTietBaiViets = new EntitySet<ChiTietBaiViet>(new Action<ChiTietBaiViet>(this.attach_ChiTietBaiViets), new Action<ChiTietBaiViet>(this.detach_ChiTietBaiViets));
			this._ChiTietPhanBiens = new EntitySet<ChiTietPhanBien>(new Action<ChiTietPhanBien>(this.attach_ChiTietPhanBiens), new Action<ChiTietPhanBien>(this.detach_ChiTietPhanBiens));
			this._LichSuChonNguoiPhanBiens = new EntitySet<LichSuChonNguoiPhanBien>(new Action<LichSuChonNguoiPhanBien>(this.attach_LichSuChonNguoiPhanBiens), new Action<LichSuChonNguoiPhanBien>(this.detach_LichSuChonNguoiPhanBiens));
			this._NguoiDung_VaiTros = new EntitySet<NguoiDung_VaiTro>(new Action<NguoiDung_VaiTro>(this.attach_NguoiDung_VaiTros), new Action<NguoiDung_VaiTro>(this.detach_NguoiDung_VaiTros));
			this._ChuyenNganh1 = default(EntityRef<ChuyenNganh>);
			this._DonVi1 = default(EntityRef<DonVi>);
			this._HocVi = default(EntityRef<HocVi>);
			this._HocHam = default(EntityRef<HocHam>);
			this._QuocGia1 = default(EntityRef<QuocGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocVi", DbType="VarChar(10)")]
		public string MaHocVi
		{
			get
			{
				return this._MaHocVi;
			}
			set
			{
				if ((this._MaHocVi != value))
				{
					if (this._HocVi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHocViChanging(value);
					this.SendPropertyChanging();
					this._MaHocVi = value;
					this.SendPropertyChanged("MaHocVi");
					this.OnMaHocViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocHam", DbType="VarChar(10)")]
		public string MaHocHam
		{
			get
			{
				return this._MaHocHam;
			}
			set
			{
				if ((this._MaHocHam != value))
				{
					if (this._HocHam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHocHamChanging(value);
					this.SendPropertyChanging();
					this._MaHocHam = value;
					this.SendPropertyChanged("MaHocHam");
					this.OnMaHocHamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="VarChar(10)")]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					if (this._DonVi1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonViChanging(value);
					this.SendPropertyChanging();
					this._MaDonVi = value;
					this.SendPropertyChanged("MaDonVi");
					this.OnMaDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenNganh", DbType="VarChar(10)")]
		public string MaChuyenNganh
		{
			get
			{
				return this._MaChuyenNganh;
			}
			set
			{
				if ((this._MaChuyenNganh != value))
				{
					if (this._ChuyenNganh1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChuyenNganhChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenNganh = value;
					this.SendPropertyChanged("MaChuyenNganh");
					this.OnMaChuyenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQG", DbType="VarChar(10)")]
		public string MaQG
		{
			get
			{
				return this._MaQG;
			}
			set
			{
				if ((this._MaQG != value))
				{
					if (this._QuocGia1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaQGChanging(value);
					this.SendPropertyChanging();
					this._MaQG = value;
					this.SendPropertyChanged("MaQG");
					this.OnMaQGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(100)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(12)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(15)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenNganh", DbType="NVarChar(100)")]
		public string ChuyenNganh
		{
			get
			{
				return this._ChuyenNganh;
			}
			set
			{
				if ((this._ChuyenNganh != value))
				{
					this.OnChuyenNganhChanging(value);
					this.SendPropertyChanging();
					this._ChuyenNganh = value;
					this.SendPropertyChanged("ChuyenNganh");
					this.OnChuyenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(200)")]
		public string DonVi
		{
			get
			{
				return this._DonVi;
			}
			set
			{
				if ((this._DonVi != value))
				{
					this.OnDonViChanging(value);
					this.SendPropertyChanging();
					this._DonVi = value;
					this.SendPropertyChanged("DonVi");
					this.OnDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocGia", DbType="NVarChar(50)")]
		public string QuocGia
		{
			get
			{
				return this._QuocGia;
			}
			set
			{
				if ((this._QuocGia != value))
				{
					this.OnQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._QuocGia = value;
					this.SendPropertyChanged("QuocGia");
					this.OnQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_ChiTietBaiViet", Storage="_ChiTietBaiViets", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<ChiTietBaiViet> ChiTietBaiViets
		{
			get
			{
				return this._ChiTietBaiViets;
			}
			set
			{
				this._ChiTietBaiViets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_ChiTietPhanBien", Storage="_ChiTietPhanBiens", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<ChiTietPhanBien> ChiTietPhanBiens
		{
			get
			{
				return this._ChiTietPhanBiens;
			}
			set
			{
				this._ChiTietPhanBiens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_LichSuChonNguoiPhanBien", Storage="_LichSuChonNguoiPhanBiens", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<LichSuChonNguoiPhanBien> LichSuChonNguoiPhanBiens
		{
			get
			{
				return this._LichSuChonNguoiPhanBiens;
			}
			set
			{
				this._LichSuChonNguoiPhanBiens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_NguoiDung_VaiTro", Storage="_NguoiDung_VaiTros", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<NguoiDung_VaiTro> NguoiDung_VaiTros
		{
			get
			{
				return this._NguoiDung_VaiTros;
			}
			set
			{
				this._NguoiDung_VaiTros.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChuyenNganh_NguoiDung", Storage="_ChuyenNganh1", ThisKey="MaChuyenNganh", OtherKey="MaChuyenNganh", IsForeignKey=true)]
		public ChuyenNganh ChuyenNganh1
		{
			get
			{
				return this._ChuyenNganh1.Entity;
			}
			set
			{
				ChuyenNganh previousValue = this._ChuyenNganh1.Entity;
				if (((previousValue != value) 
							|| (this._ChuyenNganh1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChuyenNganh1.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._ChuyenNganh1.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaChuyenNganh = value.MaChuyenNganh;
					}
					else
					{
						this._MaChuyenNganh = default(string);
					}
					this.SendPropertyChanged("ChuyenNganh1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonVi_NguoiDung", Storage="_DonVi1", ThisKey="MaDonVi", OtherKey="MaDonVi", IsForeignKey=true)]
		public DonVi DonVi1
		{
			get
			{
				return this._DonVi1.Entity;
			}
			set
			{
				DonVi previousValue = this._DonVi1.Entity;
				if (((previousValue != value) 
							|| (this._DonVi1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonVi1.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._DonVi1.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaDonVi = value.MaDonVi;
					}
					else
					{
						this._MaDonVi = default(string);
					}
					this.SendPropertyChanged("DonVi1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocVi_NguoiDung", Storage="_HocVi", ThisKey="MaHocVi", OtherKey="MaHocVi", IsForeignKey=true)]
		public HocVi HocVi
		{
			get
			{
				return this._HocVi.Entity;
			}
			set
			{
				HocVi previousValue = this._HocVi.Entity;
				if (((previousValue != value) 
							|| (this._HocVi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocVi.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._HocVi.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaHocVi = value.MaHocVi;
					}
					else
					{
						this._MaHocVi = default(string);
					}
					this.SendPropertyChanged("HocVi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocHam_NguoiDung", Storage="_HocHam", ThisKey="MaHocHam", OtherKey="MaHocHam", IsForeignKey=true)]
		public HocHam HocHam
		{
			get
			{
				return this._HocHam.Entity;
			}
			set
			{
				HocHam previousValue = this._HocHam.Entity;
				if (((previousValue != value) 
							|| (this._HocHam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocHam.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._HocHam.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaHocHam = value.MaHocHam;
					}
					else
					{
						this._MaHocHam = default(string);
					}
					this.SendPropertyChanged("HocHam");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuocGia_NguoiDung", Storage="_QuocGia1", ThisKey="MaQG", OtherKey="MaQG", IsForeignKey=true)]
		public QuocGia QuocGia1
		{
			get
			{
				return this._QuocGia1.Entity;
			}
			set
			{
				QuocGia previousValue = this._QuocGia1.Entity;
				if (((previousValue != value) 
							|| (this._QuocGia1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuocGia1.Entity = null;
						previousValue.NguoiDungs.Remove(this);
					}
					this._QuocGia1.Entity = value;
					if ((value != null))
					{
						value.NguoiDungs.Add(this);
						this._MaQG = value.MaQG;
					}
					else
					{
						this._MaQG = default(string);
					}
					this.SendPropertyChanged("QuocGia1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietBaiViets(ChiTietBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_ChiTietBaiViets(ChiTietBaiViet entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_ChiTietPhanBiens(ChiTietPhanBien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_ChiTietPhanBiens(ChiTietPhanBien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_LichSuChonNguoiPhanBiens(LichSuChonNguoiPhanBien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_LichSuChonNguoiPhanBiens(LichSuChonNguoiPhanBien entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_NguoiDung_VaiTros(NguoiDung_VaiTro entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_NguoiDung_VaiTros(NguoiDung_VaiTro entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung_VaiTro")]
	public partial class NguoiDung_VaiTro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDung;
		
		private string _MaVaiTro;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
		private EntityRef<VaiTro> _VaiTro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnMaVaiTroChanging(string value);
    partial void OnMaVaiTroChanged();
    #endregion
		
		public NguoiDung_VaiTro()
		{
			this._NguoiDung = default(EntityRef<NguoiDung>);
			this._VaiTro = default(EntityRef<VaiTro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVaiTro", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVaiTro
		{
			get
			{
				return this._MaVaiTro;
			}
			set
			{
				if ((this._MaVaiTro != value))
				{
					if (this._VaiTro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaVaiTroChanging(value);
					this.SendPropertyChanging();
					this._MaVaiTro = value;
					this.SendPropertyChanged("MaVaiTro");
					this.OnMaVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_NguoiDung_VaiTro", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.NguoiDung_VaiTros.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.NguoiDung_VaiTros.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VaiTro_NguoiDung_VaiTro", Storage="_VaiTro", ThisKey="MaVaiTro", OtherKey="MaVaiTro", IsForeignKey=true)]
		public VaiTro VaiTro
		{
			get
			{
				return this._VaiTro.Entity;
			}
			set
			{
				VaiTro previousValue = this._VaiTro.Entity;
				if (((previousValue != value) 
							|| (this._VaiTro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VaiTro.Entity = null;
						previousValue.NguoiDung_VaiTros.Remove(this);
					}
					this._VaiTro.Entity = value;
					if ((value != null))
					{
						value.NguoiDung_VaiTros.Add(this);
						this._MaVaiTro = value.MaVaiTro;
					}
					else
					{
						this._MaVaiTro = default(string);
					}
					this.SendPropertyChanged("VaiTro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuocGia")]
	public partial class QuocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaQG;
		
		private string _TenQG;
		
		private EntitySet<NguoiDung> _NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQGChanging(string value);
    partial void OnMaQGChanged();
    partial void OnTenQGChanging(string value);
    partial void OnTenQGChanged();
    #endregion
		
		public QuocGia()
		{
			this._NguoiDungs = new EntitySet<NguoiDung>(new Action<NguoiDung>(this.attach_NguoiDungs), new Action<NguoiDung>(this.detach_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQG", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaQG
		{
			get
			{
				return this._MaQG;
			}
			set
			{
				if ((this._MaQG != value))
				{
					this.OnMaQGChanging(value);
					this.SendPropertyChanging();
					this._MaQG = value;
					this.SendPropertyChanged("MaQG");
					this.OnMaQGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQG", DbType="VarChar(50)")]
		public string TenQG
		{
			get
			{
				return this._TenQG;
			}
			set
			{
				if ((this._TenQG != value))
				{
					this.OnTenQGChanging(value);
					this.SendPropertyChanging();
					this._TenQG = value;
					this.SendPropertyChanged("TenQG");
					this.OnTenQGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuocGia_NguoiDung", Storage="_NguoiDungs", ThisKey="MaQG", OtherKey="MaQG")]
		public EntitySet<NguoiDung> NguoiDungs
		{
			get
			{
				return this._NguoiDungs;
			}
			set
			{
				this._NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QuocGia1 = this;
		}
		
		private void detach_NguoiDungs(NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QuocGia1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VaiTro")]
	public partial class VaiTro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaVaiTro;
		
		private string _TenVaiTro;
		
		private EntitySet<NguoiDung_VaiTro> _NguoiDung_VaiTros;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaVaiTroChanging(string value);
    partial void OnMaVaiTroChanged();
    partial void OnTenVaiTroChanging(string value);
    partial void OnTenVaiTroChanged();
    #endregion
		
		public VaiTro()
		{
			this._NguoiDung_VaiTros = new EntitySet<NguoiDung_VaiTro>(new Action<NguoiDung_VaiTro>(this.attach_NguoiDung_VaiTros), new Action<NguoiDung_VaiTro>(this.detach_NguoiDung_VaiTros));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVaiTro", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaVaiTro
		{
			get
			{
				return this._MaVaiTro;
			}
			set
			{
				if ((this._MaVaiTro != value))
				{
					this.OnMaVaiTroChanging(value);
					this.SendPropertyChanging();
					this._MaVaiTro = value;
					this.SendPropertyChanged("MaVaiTro");
					this.OnMaVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVaiTro", DbType="NVarChar(50)")]
		public string TenVaiTro
		{
			get
			{
				return this._TenVaiTro;
			}
			set
			{
				if ((this._TenVaiTro != value))
				{
					this.OnTenVaiTroChanging(value);
					this.SendPropertyChanging();
					this._TenVaiTro = value;
					this.SendPropertyChanged("TenVaiTro");
					this.OnTenVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VaiTro_NguoiDung_VaiTro", Storage="_NguoiDung_VaiTros", ThisKey="MaVaiTro", OtherKey="MaVaiTro")]
		public EntitySet<NguoiDung_VaiTro> NguoiDung_VaiTros
		{
			get
			{
				return this._NguoiDung_VaiTros;
			}
			set
			{
				this._NguoiDung_VaiTros.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDung_VaiTros(NguoiDung_VaiTro entity)
		{
			this.SendPropertyChanging();
			entity.VaiTro = this;
		}
		
		private void detach_NguoiDung_VaiTros(NguoiDung_VaiTro entity)
		{
			this.SendPropertyChanging();
			entity.VaiTro = null;
		}
	}
}
#pragma warning restore 1591
